name: Test GitHub actions

on:
  # schedule:
  #   - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: |
          python src/main.py
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
      
      - name: Run PR Sync Manager
        uses: gohilriddhi21/github-custom-actions/action-1@main
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        with:
          VAR_1: ${{ vars.VAR_1 }}