name: Test GitHub actions

on:
  # schedule:
  #   - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true

      - name: Test with pytest
        run: |
          pytest -v -rA test/
          
      - name: Execute Python script
        run: |
          python src/main.py
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

      # Custom Actions
      - name: Run Action 1 from another repository
        uses: gohilriddhi21/github-custom-actions/action-1@main
        env:
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
        with:
          var-1: ${{ vars.VAR_1 }}

      - name: Run Action 2 from another repository
        uses: gohilriddhi21/github-custom-actions/action-2@main
        env:
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
        with:
          var-1: ${{ vars.VAR_1 }}
