name: Demo for Custom Actions

on:
  workflow_dispatch:

jobs:
  custom-action-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Basic Custom Action from another repository
        uses: gohilriddhi21/github-custom-actions/basic-custom-action@main
