name: Javascript Action

on: 
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: gohilriddhi21/github-custom-actions/javascript-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}