name: Get PR Feedback

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  feedback:
    name: PR feedback
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    #   - name: Get PR Title and Issue Number
    #     run: |
    #         pr_title=$(git log -n 1 --format='%s' HEAD)
    #         issue_number=$(git log -n 1 --format='%s' HEAD | grep -o '[#][0-9]+' | cut -d '#' -f 2)
    #         echo "PR Title: $pr_title"
    #         echo "Issue Number: $issue_number"
      - name: Switch to the PR branch
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the PR Title with the Issue number
        run: |
          echo "PR_TITLE=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} --jq '.title')" >> $GITHUB_ENV 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run PR Feedback
        uses: gohilriddhi21/github-custom-actions/action-1@main
        with:
            pr-title: $PR_TITLE
            issue-number: ${{ github.event.issue.number }}
