name: Get PR Feedback

on:
  # workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  feedback:
    name: PR feedback
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Switch to the PR branch
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the PR Title with the Issue number
        run: |
          echo "PR_TITLE=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} --jq '.title')" >> $GITHUB_ENV 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run PR Feedback
        uses: gohilriddhi21/github-custom-actions/pr-feedback@main
        with:
            pr-title: $PR_TITLE
            issue-number: ${{ github.event.issue.number }}
