name: Demo Workflow

on:
  # schedule:
  #   - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch: # Add this line to manually trigger your workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'


